# Generated by Django 2.0.4 on 2018-04-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(default='Developer', max_length=30),
        ),
        migrations.AddField(
            model_name='manager',
            name='job_title',
            field=models.CharField(default='Manager', max_length=30),
        ),
    ]
